import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# Load the data
data = pd.read_csv('cleaned_data.csv')

# 1. Top 10 Publishers by Total Games Released (Bar Chart)
top_publishers = data['publisher'].value_counts().head(10)
plt.figure(figsize=(14, 8))
top_publishers.plot(kind='bar', color='skyblue', edgecolor='black')
plt.title('Top 10 Publishers by Total Games Released', fontsize=16)
plt.xlabel('Publisher', fontsize=14)
plt.ylabel('Number of Games', fontsize=14)
plt.xticks(rotation=45, ha='right')
plt.grid(axis='y', alpha=0.3)
plt.show()

# 2. Trends in Total Sales Over Time (Line Chart)
data['release_date'] = pd.to_datetime(data['release_date'], errors='coerce')
sales_by_year = data.groupby(data['release_date'].dt.year)['total_sales'].sum()
plt.figure(figsize=(14, 8))
sales_by_year.plot(kind='line', marker='o', color='green')
plt.title('Trends in Total Sales Over Time', fontsize=16)
plt.xlabel('Year', fontsize=14)
plt.ylabel('Total Sales (in millions)', fontsize=14)
plt.grid(alpha=0.3)
plt.show()

# 3. Distribution of Critic Scores by Genre (Boxplot)
plt.figure(figsize=(14, 8))
sns.boxplot(data=data, x='genre', y='critic_score', palette='Set3')
plt.title('Distribution of Critic Scores by Genre', fontsize=16)
plt.xlabel('Genre', fontsize=14)
plt.ylabel('Critic Score', fontsize=14)
plt.xticks(rotation=45, ha='right')
plt.grid(axis='y', alpha=0.3)
plt.show()

# 4. Correlation Between Sales and Critic Score (Heatmap)
sales_and_scores = data[['critic_score', 'total_sales', 'na_sales', 'jp_sales', 'pal_sales', 'other_sales']].dropna()
correlation_matrix = sales_and_scores.corr()
plt.figure(figsize=(10, 8))
sns.heatmap(correlation_matrix, annot=True, fmt=".2f", cmap='coolwarm', linewidths=0.5)
plt.title('Correlation Between Sales and Critic Score', fontsize=16)
plt.show()

# 5. Console Market Share by Genre (Stacked Bar Chart)
genre_platform_sales = data.groupby(['genre', 'console'])['total_sales'].sum().unstack()
plt.figure(figsize=(14, 10))
genre_platform_sales.plot(kind='bar', stacked=True, colormap='viridis')
plt.title('Console Market Share by Genre', fontsize=16)
plt.xlabel('Genre', fontsize=14)
plt.ylabel('Total Sales (in millions)', fontsize=14)
plt.legend(title='Console', bbox_to_anchor=(1.05, 1), loc='upper left')
plt.xticks(rotation=45, ha='right')
plt.tight_layout()
plt.show()

# 6. Distribution of Total Sales (Histogram)
plt.figure(figsize=(14, 8))
plt.hist(data['total_sales'], bins=20, color='lightcoral', edgecolor='black', alpha=0.7)
plt.title('Distribution of Total Sales', fontsize=16)
plt.xlabel('Total Sales (in millions)', fontsize=14)
plt.ylabel('Frequency', fontsize=14)
plt.grid(axis='y', alpha=0.3)
plt.show()

# 7. Genre Market Share (Pie Chart)
genre_counts = data['genre'].value_counts()
plt.figure(figsize=(14, 10))
plt.pie(genre_counts, labels=genre_counts.index, autopct='%1.1f%%', startangle=140, colors=plt.cm.tab20.colors)
plt.title('Genre Market Share', fontsize=16)
plt.show()

# 8. Critic Score vs Total Sales (Scatter Plot)
plt.figure(figsize=(14, 8))
plt.scatter(data['critic_score'], data['total_sales'], alpha=0.6, color='skyblue')
plt.title('Critic Score vs Total Sales', fontsize=16)
plt.xlabel('Critic Score', fontsize=14)
plt.ylabel('Total Sales (in millions)', fontsize=14)
plt.grid(alpha=0.3)
plt.show()

# 9. Distribution of Sales in North America (Histogram)
plt.figure(figsize=(14, 8))
plt.hist(data['na_sales'].dropna(), bins=20, color='lightgreen', edgecolor='black', alpha=0.7)
plt.title('Distribution of Sales in North America', fontsize=16)
plt.xlabel('North America Sales (in millions)', fontsize=14)
plt.ylabel('Frequency', fontsize=14)
plt.grid(axis='y', alpha=0.3)
plt.show()

# 10. Sales by Genre and Platform (Stacked Bar Chart)
genre_platform_sales = data.groupby(['genre', 'console'])['total_sales'].sum().unstack()
plt.figure(figsize=(14, 10))
genre_platform_sales.plot(kind='bar', stacked=True, colormap='viridis')
plt.title('Sales by Genre and Platform', fontsize=16)
plt.xlabel('Genre', fontsize=14)
plt.ylabel('Total Sales (in millions)', fontsize=14)
plt.legend(title='Console', bbox_to_anchor=(1.05, 1), loc='upper left')
plt.xticks(rotation=45, ha='right')
plt.tight_layout()
plt.show()

# 11. Top 5 Games with Highest Sales in North America (Bar Chart)
top_na_sales = data[['title', 'na_sales']].sort_values(by='na_sales', ascending=False).head(5)
plt.figure(figsize=(14, 8))
sns.barplot(data=top_na_sales, x='na_sales', y='title', palette='coolwarm')
plt.title('Top 5 Games with Highest Sales in North America', fontsize=16)
plt.xlabel('North America Sales (in millions)', fontsize=14)
plt.ylabel('Game Title', fontsize=14)
plt.grid(axis='x', alpha=0.3)
plt.show()

# 12. Sales Distribution by Platform (Boxplot)
plt.figure(figsize=(14, 8))
sns.boxplot(data=data, x='console', y='total_sales', palette='Set2')
plt.title('Sales Distribution by Platform (Console)', fontsize=16)
plt.xlabel('Console', fontsize=14)
plt.ylabel('Total Sales (in millions)', fontsize=14)
plt.xticks(rotation=45, ha='right')
plt.grid(axis='y', alpha=0.3)
plt.show()

# 13. Sales Correlation by Region (Heatmap)
sales_regions = data[['na_sales', 'jp_sales', 'pal_sales', 'other_sales']]
correlation_matrix = sales_regions.corr()
plt.figure(figsize=(10, 8))
sns.heatmap(correlation_matrix, annot=True, fmt=".2f", cmap='coolwarm', linewidths=0.5)
plt.title('Sales Correlation by Region', fontsize=16)
plt.show()

# 14. Distribution of PAL Sales (Histogram)
plt.figure(figsize=(14, 8))
plt.hist(data['pal_sales'].dropna(), bins=20, color='blue', edgecolor='black', alpha=0.7)
plt.title('Distribution of PAL Sales', fontsize=16)
plt.xlabel('PAL Sales (in millions)', fontsize=14)
plt.ylabel('Frequency', fontsize=14)
plt.grid(axis='y', alpha=0.3)
plt.show()

# 15. Average Sales by Publisher (Bar Chart)
average_sales_publisher = data.groupby('publisher')['total_sales'].mean().sort_values(ascending=False).head(10)
plt.figure(figsize=(14, 8))
average_sales_publisher.plot(kind='bar', color='purple', edgecolor='black')
plt.title('Average Sales by Top 10 Publishers', fontsize=16)
plt.xlabel('Publisher', fontsize=14)
plt.ylabel('Average Total Sales (in millions)', fontsize=14)
plt.xticks(rotation=45, ha='right')
plt.grid(axis='y', alpha=0.3)
plt.show()

# 16. Distribution of Sales in Japan (Histogram)
plt.figure(figsize=(14, 8))
plt.hist(data['jp_sales'].dropna(), bins=20, color='orange', edgecolor='black', alpha=0.7)
plt.title('Distribution of Sales in Japan', fontsize=16)
plt.xlabel('Japan Sales (in millions)', fontsize=14)
plt.ylabel('Frequency', fontsize=14)
plt.grid(axis='y', alpha=0.3)
plt.show()

# 17. Top 10 Developers by Total Sales (Bar Chart)
top_developers = data.groupby('developer')['total_sales'].sum().sort_values(ascending=False).head(10)
plt.figure(figsize=(14, 8))
top_developers.plot(kind='bar', color='teal', edgecolor='black')
plt.title('Top 10 Developers by Total Sales', fontsize=16)
plt.xlabel('Developer', fontsize=14)
plt.ylabel('Total Sales (in millions)', fontsize=14)
plt.xticks(rotation=45, ha='right')
plt.grid(axis='y', alpha=0.3)
plt.show()
